---
-
  hosts: all
  tasks:
    -
      apt:
        update_cache: true
      become: true
      name: "Update APT package manager repositories cache"
    -
      apt:
        name: "{{ packages }}"
        state: present
      become: true
      name: "Install Java using Ansible"
      vars:
        packages:
          - openjdk-8-jdk
